version: '3.9'

services:

  redis:
    container_name: redis
    restart: always
    image: redis:6.2-alpine
    ports:
      - '6379:6379'

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379